#!/usr/bin/env bash
# sourced by interactive bash sessions

[ -z "$BASH_VERSION" ] && { echo "Source this in bash only"; return 1; }

if [ -r "$HOME/.config/shell-path.sh" ]; then
    . "$HOME/.config/shell-path.sh"
fi
[[ $- != *i* ]] && return

shopt -s checkwinsize cmdhist histappend histverify no_empty_cmd_completion
HISTIGNORE="[ ]*:&:[bf]g:clear:exit"
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=$HISTSIZE
HISTFILE="$HOME/.local/state/history/bash.history"

export INPUTRC="$HOME/.inputrc"

[ -r "$HOME/.config/shell-settings.sh" ] && . "$HOME/.config/shell-settings.sh"
type -p atuin >/dev/null && eval "$(atuin init bash)"
type -p zoxide >/dev/null && eval "$(zoxide init --cmd cd bash)"
