#!/usr/bin/env bash
# sourced by interactive bash sessions

[ -z "$BASH_VERSION" ] && { echo "Source this in bash only"; return 1; }

[ -r "$HOME/.config/shell-path.sh" ] && . "$HOME/.config/shell-path.sh"
[[ $- != *i* ]] && return

shopt -s checkwinsize cmdhist histappend histverify no_empty_cmd_completion
HISTIGNORE="[ ]*:&:[bf]g:clear:exit"
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=$HISTSIZE
HISTFILE="$XDG_STATE_HOME/history/bash.history"

export INPUTRC=~/.inputrc

[ -r "$XDG_CONFIG_HOME/shell-settings.sh" ] && . "$XDG_CONFIG_HOME/shell-settings.sh"
type -p fzf >/dev/null && eval "$(fzf --bash)"
type -p zoxide >/dev/null && eval "$(zoxide init --cmd cd bash)"
