#!/bin/zsh
# sourced by interactive zsh only (after .zshenv)
# debug with: env -i HOME="$HOME" PATH="/usr/bin:/bin" zsh -ilxc 'echo "PATH=$PATH"'

[ -z "$ZSH_VERSION" ] && { echo "Source this in zsh only"; return 1; }
[[ -o interactive ]] || return 0

typeset -U path PATH fpath

HISTFILE="$XDG_STATE_HOME/history/zsh.history"
HISTSIZE=50000
SAVEHIST=50000
WORDCHARS='._~'

setopt HIST_VERIFY
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_LEX_WORDS  # shell-lexer word splitting for history (!$, !^, etc.)
setopt HIST_NO_FUNCTIONS  # don't store function definitions in history
setopt AUTO_LIST  # list on ambiguous completion

LISTMAX=0  # Never ask "do you want to see all X?" completions
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'  # Case-insensitive fuzzy match
zstyle ':completion:*' verbose yes  # Show command/flag descriptions
zstyle ':completion:*' group-name ''  # Group matches by category
zstyle ':completion:*' rehash true  # Automatically rehash when the PATH changes
zstyle ':completion:*:descriptions' format '%F{blue}-- %d --%f'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' completer _extensions _complete _approximate  # Smarter completer order

[ -r "$XDG_CONFIG_HOME/shell-settings.sh" ] && . "$XDG_CONFIG_HOME/shell-settings.sh"

fpath+=("$XDG_DATA_HOME/zsh/site-functions")
autoload -Uz compinit
zcompdump_file="$XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION"
if [ -f "$zcompdump_file" ]; then
    compinit -C -d "$zcompdump_file"
else
    compinit -d "$zcompdump_file"
fi

# Load plugins after compinit
#source ~/.zsh/plugins/fzf-tab/fzf-tab.plugin.zsh
#zstyle ':fzf-tab:complete:*:*' fzf-preview \
#  'if [ -d $realpath ]; then eza --icons --color=always --tree --level=2 $realpath; else bat --color=always --style=numbers $realpath; fi'
#source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

zmodload zsh/terminfo 2>/dev/null  # Ensure $terminfo is available

# Ctrl+Left / Ctrl+Right: use terminfo when available, fall back to common sequences
[[ -n ${terminfo[kLFT5]} ]] && bindkey "${terminfo[kLFT5]}" backward-word
[[ -n ${terminfo[kRIT5]} ]] && bindkey "${terminfo[kRIT5]}" forward-word
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word

# Home / End (begin/end of line): terminfo + common fallbacks
[[ -n ${terminfo[khome]} ]] && bindkey "${terminfo[khome]}" beginning-of-line
[[ -n ${terminfo[kend]}  ]] && bindkey "${terminfo[kend]}"  end-of-line
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
bindkey '^[[1~' beginning-of-line
bindkey '^[[4~' end-of-line
bindkey '^[[3;5~' kill-line  # ctrl+delete
bindkey '^H' backward-kill-word  # Ctrl+Backspace
bindkey '^[[127;5u' backward-kill-word  # CSI-u for ctrl+backspace

(( $+commands[fzf] )) && source <(fzf --zsh)
(( $+commands[zoxide] )) && eval "$(zoxide init --cmd cd zsh)"
