#!/bin/zsh

# Show status of a local git repo, how many commits it is behind origin and whether changes are pending

set -eu

FOLDER=${1:-$PWD}
FOLDER=$(cd "$FOLDER" && pwd)
TITLE=${TITLE:-$(basename "$FOLDER")}
PULL=${PULL:-}

git -C "$FOLDER" fetch -q
LOCAL=$(git -C "$FOLDER" rev-parse @)
REMOTE=$(git -C "$FOLDER" rev-parse "@{u}")
BEHIND=0
if [[ "$LOCAL" != "$REMOTE" ]]; then
    BEHIND=$(git -C "$FOLDER" rev-list --count $LOCAL..$REMOTE)
fi
PENDING=$(git -C "$FOLDER" status --porcelain | wc -l | xargs)

if [[ $BEHIND = 0  && $PENDING = 0 ]]; then
    echo "[$TITLE] ✨ Up to date"
    exit 0
fi

MESSAGE=
if [[ "$BEHIND" -gt 0 ]]; then
    MESSAGE="$BEHIND behind"
    if [[ -n "$PULL" && $PENDING = 0 ]]; then
        git -C "$FOLDER" pull
        echo "[$TITLE] was $MESSAGE"
        exit $BEHIND
    fi
fi

if [[ "$PENDING" -gt 0 ]]; then
    [[ -n "$MESSAGE" ]] && MESSAGE="$MESSAGE, "
    MESSAGE="$MESSAGE$PENDING pending"
    echo "[$TITLE] $MESSAGE:"
    git -C "$FOLDER" status --short
else
    echo "[$TITLE] $MESSAGE"
fi
