initial-command = ~/bin/join-tmux demo

title = demo
font-size = 25
font-thicken = false
window-position-x = 10
window-position-y = 10
window-width = 170
window-height = 46
background-image = ghostty-logo.png
