config-file = ./common.conf

initial-command = ~/bin/join-tmux demo

title = demo
macos-icon = retro
font-size = 25
font-thicken = false

window-position-x = 20
window-position-y = 5
window-width = 170
window-height = 45
background-image = netflix-n.png
