auto_sync = false  # automatically sync, when logged in
enter_accept = false  # execute command on enter
update_check = false  # automatically check for updates
search_mode = "fuzzy"  # daemon-fuzzy

filter_mode = "host"  # global, host, session,  directory, workspace, session-preload
inline_height = 8  # max number of lines for TUI
invert = false  # invert == put the search bar at the top
style = "compact"
show_preview = true
show_help = false  # show atuin version + amount of commands in history
show_tabs = false  # tabs for search and inspect

# defaults for shell up-key
search_mode_shell_up_key_binding = "fuzzy"
filter_mode_shell_up_key_binding = "host"
inline_height_shell_up_key_binding = 6

#[daemon]
#enabled = true
#autostart = true

[keys]
scroll_exits = false  # exit when scrolled past the last or first entry
exit_past_line_start = false  # exit TUI when scrolling left while the cursor is at the start of the line
accept_past_line_end = true  # right arrow key performs the same functionality as Tab

[search]
authors = ["$all-user", "$all-agent"]
filters = ["session-preload", "directory", "workspace", "host", "session"]
recency_score_multiplier = 2.0
frequency_score_multiplier = 1.0
frecency_score_multiplier = 2.0

[logs]
enabled = true
dir = "~/.local/share/atuin/logs"
level = "info"
retention = 4

[ui]
columns = ["duration", { type = "user", width = 5 }, "time", "command"]
