brew "btop"
brew "dua-cli"
brew "duf"
# brew "dust"
brew "fd"
# brew "hyperfine"
brew "pstree"
# brew "tailspin"
brew "tmux"
brew "tokei"
brew "tre-command"
brew "xh"
brew "zoxide"

if ENV["USER"] == "zoran"
    brew "uv"
end

if OS.mac?
  cask "appcleaner"
  cask "font-symbols-only-nerd-font"
  cask "ghostty"
  cask "google-chrome"
  cask "iterm2"
  cask "shottr"
  cask "sublime-text"
  cask "raycast"

  if ENV["USER"] == "zoran"
    cask "1password"
    cask "discord"
    cask "firefox"
    cask "iina"
    cask "onyx"
    cask "quicklook-video"
  end
end
